deploy:
  provider: puppetforge
  user: instana
  password:
    secure: "R+J83oVl6f5iPZgAbZZY1P4Thzsec7HxzezPL2AZtUm/+iMz1JQR+3YdR/W1gEzCgyw6Llbzv4gA7VcdNrgxOZYeGhIOnu2ez8eRPxMr+HWzYDVK6Y64wdQ+Ki3lU4lp8XtIEMHgLNuO4cWaBFUaeNtJlqmTfV604EXGSGZPH4lZ4SpT/DnmYjErl0Idr8g8urrUTO0awMg6omawytQ6PP2WSMN0pODcqUMES25LkbH96Ah45FKtQuFjbYNG9UIW1hzTNWCIZ5JIFA5TthvIonajgTnpMKpcLpkNH4hhoWZe4IB/7mfE+8TpXEsQmHgVTlZBNTOVd5BkuJle4V4T6eD0W4BzItq6DesaIHVw9gJQQiiMtJGfsuqTPS8NYIAJ7Wc7amyntGjnDBldolD+55Yd2kqRGQrP3XxWRpxOg0JGv6Ax6IXdGQTvRO9Fi/OyUCTzI8zWqnrSWI5TWgFEKEvbiXyiI5uP9krZBDtWxE2kqDIVf78pACxQMPg05TZiVe0tA6DfC5SjwCz4/GWGwccumyHK6NqGZzIPZogz2w44PKfwU0mKJbqxCrIHUloZVUFGLqN9qi90Yy/H2jNxFN8kPktqWY+xdLsH8093mgvBfNs9UeDwazGI8FaQ6kz2Q83xch91qqwEuiAzAMgjM+UpyNxcJspdWdxfcuulhjM="
  on:
    tags: true
    all_branches: true
