deploy:
  provider: puppetforge
  user: instana
  secure: "fNhAqtIqaR8qJguV2nukGJfBPJedaFpR0p2k6Mf6c2qLQdnu/OTS6WeY+uZ16yfcCuLM+yb1/M2c686J/KSvF2VzMAKpTiBJyFGWhuGIqH61nN5WM+LDOztXQChgJLJdkraJ9E/bI2MSSTQQDZ+kI1myzB1eQkuojp2nSWyFrR8YWfY8yKF6QvYEs8PVHdecs7bib6VTxp9NHVy2DIaITBHvUfURTCAyBm5AXJqiuZecTqYnr1m07pjwJ0l/zwNwlpYfZdsbOUmtKEQMD4utBOhvYFBL4ql/pWGqT137muD4iac1nvo+rf9rYNZMiub25IzOx3Ijs/WP+7ZZXeJb4zqxEC72LoNjvWh4Ftf+w5ONnv/wcyRxPYORjPJn6itq/yQIEXOv/pY0QIjCpp8f67EIhIJ6LTsPNZVRARIND5can+nbcjBC6jJ8HsTA920LLAEhEQDtU6p5isTGHI6ASFePBTcd6uL5p30KY9ryuXchaglc7Z0VLiGGWrCbqujPJi8SqwvBnKrRFbyUsbkWIU6ncGGigttqqyaxENDUQ9apbR71gz0mp+6YK9OnPJfkIN9GVIoCbVIElNgjITq9VtnxuDqOSpVowXr39Jh9k/7Utmn+z0iq0vnkL43DHQY3lTJyD6vFPyR38xaV3peyBeJ+M55Iaj0nNDg+m1MCjFQ="
  on:
    tags: true
    all_branches: true
